export interface TranscriptLine {
  text: string;
  duration: number;
  offset: number;
  lang: string;
}

export interface VideoMeta {
  videoId: string;
  title: string;
  author: string;
  channelId: string;
  lengthSeconds: number;
  viewCount: number;
  description: string;
  keywords: string[];
  thumbnails: Array<{ url: string; width: number; height: number }>;
  isLiveContent: boolean;
}

export interface TranscriptWithMeta {
  meta: VideoMeta;
  lines: TranscriptLine[];
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

export interface TranscriptOptions {
  lang?: string;
  userAgent?: string;
  useHttp?: boolean;
  includeMeta?: boolean;
  customFetch?: (url: string, init?: RequestInit) => Promise<Response>;
  signal?: AbortSignal;
  cache?: CacheStore;
  cacheTTL?: number;
  retries?: number;
  retryDelay?: number;
}

export interface CacheStore {
  get(key: string): Promise<string | null>;
  set(key: string, value: string, ttl?: number): Promise<void>;
}

export interface InternalCaptionTrack {
  baseUrl?: string;
  url?: string;
  languageCode: string;
  name?: { simpleText?: string };
  kind?: string;
}

export interface InnertubePlayerResponse {
  playabilityStatus?: { status?: string };
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    channelId?: string;
    lengthSeconds?: string;
    viewCount?: string;
    shortDescription?: string;
    keywords?: string[];
    thumbnail?: { thumbnails?: Array<{ url: string; width: number; height: number }> };
    isLiveContent?: boolean;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InternalCaptionTrack[];
    };
  };
  playerCaptionsTracklistRenderer?: {
    captionTracks?: InternalCaptionTrack[];
  };
}

export type VideoTranscriptStatus = "success" | "failed";

export interface VideoTranscriptResult {
  videoId: string;
  title: string;
  position: number;
  status: VideoTranscriptStatus;
  lines?: TranscriptLine[];
  error?: string;
}

export interface PlaylistTranscriptResult {
  playlistId: string;
  totalVideos: number;
  requestedRange: [number, number];
  succeeded: number;
  failed: number;
  results: VideoTranscriptResult[];
}

export interface PlaylistTranscriptOptions extends TranscriptOptions {
  apiKey: string;
  from?: number;
  to?: number;
  concurrency?: number;
  onProgress?: (
    done: number,
    total: number,
    videoId: string,
    status: VideoTranscriptStatus,
  ) => void;
}
