export interface TranscriptLine {
  text: string;
  duration: number;
  offset: number;
  lang: string;
}

export interface VideoMeta {
  videoId: string;
  title: string;
  author: string;
  channelId: string;
  lengthSeconds: number;
  viewCount: number;
  description: string;
  keywords: string[];
  thumbnails: Array<{ url: string; width: number; height: number }>;
  isLiveContent: boolean;
}

export interface TranscriptWithMeta {
  meta: VideoMeta;
  lines: TranscriptLine[];
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

export interface TranscriptOptions {
  lang?: string;
  userAgent?: string;
  useHttp?: boolean;
  includeMeta?: boolean;
  customFetch?: (url: string, init?: RequestInit) => Promise<Response>;
  signal?: AbortSignal;
}

export interface InternalCaptionTrack {
  baseUrl?: string;
  url?: string;
  languageCode: string;
  name?: { simpleText?: string };
  kind?: string;
}

export interface InnertubePlayerResponse {
  playabilityStatus?: { status?: string };
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    channelId?: string;
    lengthSeconds?: string;
    viewCount?: string;
    shortDescription?: string;
    keywords?: string[];
    thumbnail?: { thumbnails?: Array<{ url: string; width: number; height: number }> };
    isLiveContent?: boolean;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InternalCaptionTrack[];
    };
  };
  playerCaptionsTracklistRenderer?: {
    captionTracks?: InternalCaptionTrack[];
  };
}
