import { TranscriptClient, toPlainText } from "../packages/core/src/modules/transcript.js";

const client = new TranscriptClient({ lang: "en" });

async function main() {
  const videoId = "dQw4w9WgXcQ";

  console.log("=== TranscriptClient with shared config ===\n");
  console.log("Default language: en\n");

  console.log("--- transcribe() ---\n");
  const lines = await client.transcribe(videoId);

  if (Array.isArray(lines)) {
    console.log(`Got ${lines.length} lines (lang: ${lines[0]?.lang})\n`);
    console.log(toPlainText(lines.slice(0, 5)));
  }

  console.log("\n--- availableTracks() ---\n");
  const tracks = await client.availableTracks(videoId);

  for (const track of tracks) {
    const auto = track.isAutoGenerated ? " (auto)" : "";
    console.log(`  ${track.languageCode}: ${track.languageName}${auto}`);
  }
}

main().catch(console.error);
