import { listCaptionTracks } from "../packages/core/src/modules/transcript.js";

const VIDEO_ID = "dQw4w9WgXcQ";

async function main() {
  console.log(`Fetching caption tracks for: ${VIDEO_ID}\n`);

  const tracks = await listCaptionTracks(VIDEO_ID);

  console.log(`Found ${tracks.length} caption track(s):\n`);

  for (const track of tracks) {
    const auto = track.isAutoGenerated ? " (auto-generated)" : "";
    console.log(`  ${track.languageCode} — ${track.languageName}${auto}`);
  }
}

main().catch(console.error);
